### ISSUE TITLE
Hide tabs manual

### ISSUE THREAD

**Issue by NN---** [fonse/tab-workspaces#24]
>If you know any better way to hide the tabs, please let me know.

Adding this file to <profile>\chrome\userChrome.css hides top tabs.

```css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

#TabsToolbar, #PersonalToolbar {
    visibility: collapse;
}

#sidebar-header {
    visibility: collapse !important;
}
```
